### ISSUE TITLE
After gets called n-times

### ISSUE THREAD

**Issue by matti** [chaps-io/gush#46] opened 2017-11-04 15:52 UTC
Tried the README's example:

```
class SimpleWorkflow < Gush::Workflow
  def configure
    run FirstDownloadJob
    run SecondDownloadJob

    run SaveJob, after: [FirstDownloadJob, SecondDownloadJob]
  end
end
```

`SaveJob` will be invoked twice:

```
2017-11-04T15:51:12.522Z 5060 TID-ovvcwd854 Gush::Worker JID-f3bddd0cf26cd11492d97a6b INFO: start
2017-11-04T15:51:12.527Z 5060 TID-ovvcwd95s Gush::Worker JID-beda8811a9c7976ef33abd41 INFO: start
SecondDownloadJob#perform {}
FirstDownloadJob#perform {}
2017-11-04T15:51:12.569Z 5060 TID-ovvcwcmx8 Gush::Worker JID-18a48a9a6ce45b6aee78bb35 INFO: start
2017-11-04T15:51:12.571Z 5060 TID-ovvcwd854 Gush::Worker JID-f3bddd0cf26cd11492d97a6b INFO: done: 0.049 sec
2017-11-04T15:51:12.580Z 5060 TID-ovvcwd9o4 Gush::Worker JID-b98176b881db8a61e8f7cdb9 INFO: start
2017-11-04T15:51:12.586Z 5060 TID-ovvcwd95s Gush::Worker JID-beda8811a9c7976ef33abd41 INFO: done: 0.059 sec
SaveJob#perform {}
2017-11-04T15:51:12.597Z 5060 TID-ovvcwcmx8 Gush::Worker JID-18a48a9a6ce45b6aee78bb35 INFO: done: 0.029 sec
SaveJob#perform {}
2017-11-04T15:51:12.601Z 5060 TID-ovvcwd9o4 Gush::Worker JID-b98176b881db8a61e8f7cdb9 INFO: done: 0.02 sec
```

**Comment by matti** [comment] 2017-11-04 15:53
Same with:
```
class SimpleWorkflow < Gush::Workflow
  def configure
    run FirstDownloadJob, before: SaveJob
    run SecondDownloadJob, before: SaveJob

    run SaveJob#, after: [FirstDownloadJob, SecondDownloadJob]
  end
end
```

**Comment by matti** [comment] 2017-11-04 15:57
actually... ...this is intended behaviour? Is there a way to call SaveJob just once?

**Comment by matti** [comment] 2017-11-04 15:58
so that both DownloadJobs would be completed before

**Comment by pokonski** [comment] 2017-11-04 16:00
It definitely should only trigger the SaveJob only once. Will reproduce and
fix, because this is a regression :(

**Comment by matti** [comment] 2017-11-04 16:01
Actually, I'm not sure if this behaviour is a bug - it follows the diagram nicely - each notification job triggers another job... But yes, this was the main use case for using gush for me.

**Comment by pokonski** [comment] 2017-11-04 16:05
Yeah this is unintended, it should only trigger the job if all of its
dependencies have finished successfully. So only the second check should
see that the other job finished and only then should enqueue the SaveJob. I
suspect the state is incorrectly persisted along the way.

**Comment by matti** [comment] 2017-11-04 16:13
clarification: yes, it's a bug - but also an interesting feature that kinda follows the diagram.

**Comment by pokonski** [comment] 2017-11-04 16:14
Ha, maybe that also needs a configuration option :D

**Comment by dmitrypol** [comment] 2017-12-17 16:20
I also experienced this behavior in my tests

**Comment by erated** [comment] 2018-01-21 12:59
Any updates about this? We have encountered this as well.

**Comment by tanin** [comment] 2018-01-21 13:00
Hi, is there any news about this bug?

**Comment by pokonski** [comment] 2018-02-05 04:48
@erated @tanin haven't had a chance to investigate, but can you share your minimal case to reproduce, too? Will help tracking it down.

**Comment by matti** [comment] 2018-07-10 17:05
@pokonski isnt my original example in the beginning of thia thread enough?

**Comment by pokonski** [comment] 2018-07-10 20:00
@matti it's enough, I reproduced it in specs but seems to be related to race condition when using an async adapter for ActiveJob.

**Comment by pokonski** [comment] 2018-07-10 20:52
Alright, master now contains a fix for this issue @dmitrypol @matti @tanin. Please let me know if it helps!

This should only be an issue for a jobs finishing almost at the same time, most apparent in tests because usually the jobs are empty and execute close to each other. I added a mutex so only one of the ancestors can en-queue his descendant at any given time while others have to wait.

**Comment by matti** [comment] 2018-07-11 05:47
But atleast I didn't use ActiveJob. let's test this..

**Comment by pokonski** [comment] 2018-07-11 07:37
@matti it's not actually related to ActiveJob, it's simply caused when jobs are running in parallel and both trigger their descendant. Now I put a lock so triggering new jobs is run one at a time, solving the race condition.

**Comment by lastobelus** [comment] 2018-10-04 21:14
> @matti it's not actually related to ActiveJob, it's simply caused when jobs are running in parallel and both trigger their descendant veeery close to each other. Now I put a lock so triggering new jobs is run one at a time, solving the race condition.

is this bug fixed then?

**Comment by matti** [comment] 2018-10-05 05:45
@pokonski ?

**Comment by pokonski** [comment] 2018-10-05 07:45
Fixed in https://github.com/chaps-io/gush/commit/49000a30fd34ac21cabdc7d2c24ffbfa3b113bb9

**Closed** 2018-10-05 09:18 UTC
Labels: bug
